# Generated by Django 4.2.16 on 2026-05-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='grupo_venta',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
